import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../stories/Navbar'
import { getSession } from 'next-auth/react'

interface User {
  name: string
  email: string
  image: string
}

interface Session {
  user: User
  expires: string
}

const Home: NextPage<{ data: string; session: Session }> = ({
  data,
  session,
}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <h1>{data}</h1>
        {session && (
          <>
            <h1>{session.user.name}</h1>
            <h1>{session.user.email}</h1>
            <h1>{session.user.image}</h1>
            <h1>{session.expires}</h1>
          </>
        )}
      </main>

      <footer></footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const session = await getSession(ctx)
  return {
    props: {
      session,
      data: session ? 'List of 100 personalizedblogs' : 'List of free blogs',
    },
  }
}

export default Home
