import type { NextPage } from 'next'
import Head from 'next/head'
import Button from '../stories/Button'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button size="big">Big Button</Button>
        <Button size="small">Small Button</Button>
        <Button>Normal Button</Button>
      </main>

      <footer></footer>
    </div>
  )
}

export default Home
